source "https://rubygems.org"

gem "rails", "~> 8.0.0"
gem "wasmify-rails", "~> 0.3.1"

# rails new gems
gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

gem "bcrypt", "~> 3.1.7"

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "image_processing", "~> 1.2"
